sudo: required

services:
  - docker

before_install:
  - docker build -t vishalrajole/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run vishalrajole/react-test npm test -- --coverage

after_success:
  - docker build -t vishalrajole/client ./client
  - docker build -t vishalrajole/nginx ./nginx
  - docker build -t vishalrajole/server ./server
  - docker build -t vishalrajole/worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push vishalrajole/client
  - docker push vishalrajole/nginx
  - docker push vishalrajole/server
  - docker push vishalrajole/worker
